# Generated by Django 3.0.6 on 2020-05-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphyapp', '0002_story_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_image',
        ),
    ]
