# Generated by Django 3.0.6 on 2020-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphyapp', '0004_story_story_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=200)),
                ('grapher_name', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('story_description', models.TextField()),
                ('story_video', models.FileField(upload_to='storyvideos')),
            ],
        ),
        migrations.RenameModel(
            old_name='Story',
            new_name='ImageStory',
        ),
    ]
