# Generated by Django 3.0.6 on 2020-05-30 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphyapp', '0005_auto_20200530_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostory',
            name='story_video',
            field=models.FileField(upload_to='storyvideos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi'])]),
        ),
    ]
